### ISSUE TITLE
fmpapi R package

### ISSUE THREAD

**Issue by jpiburn** [tonytrevisan/fmpcloudr#1]
Hi Tony,

This package looks great. A few months back while I was away from work I put some time into making a similar R package for using the fmp API, [fmpapi](https://jpiburn.github.io/fmpapi/). It was a fun side project that I hoped I would be able to keep updated and maintain but, of course, I over estimated how much time I would be able to spend on it once life got back to normal :) 

I wanted to invite you to take a look and tell you to feel free to borrow/steal/pull out any code you might find useful. The overall goal for me is there be a great R package for the fmp API and if you are planning on actively maintaining this one, I would be happy to deprecate the `fmpapi` package and consolidate the effort into `fmpclouldr` 

Let me know what you think and I can update the `fmpapi` package documentation appropriately 

 Jesse

**Comment by altanalytics** [comment]
Jesse,

Thanks for reaching out! Unfortunately I had nearly completed the ‘fmpcloudr’ package by the time I came across ‘fmpapi’. I should have reached out sooner to connect. I do plan to keep it updated going forward because I use it pretty regularly in my job. I know that FMP is planning to release live bid/ask data soon so will certainly incorporate that component. 

I will take a closer look at ‘fmpapi’ and see if I can take anything. Sorry to have duplicated efforts. Happy to also have you contribute if you catch anything that could be added.
