### ISSUE TITLE
fmpc_economic_results doesn't work.

### ISSUE THREAD

**Issue by piravi80** [tonytrevisan/fmpcloudr#5]
Hi, I simply run this line:
fmpc_economic_results(event = 'adpEmploymentChange', country = 'US')

this is the output:
# A tibble: 0 × 0
Warning message:
Not Found

**Comment by altanalytics** [comment]
It looks like they took out the endpoint from fmpcloud: https://fmpcloud.io/documentation

I found a similar one on their sister site: https://site.financialmodelingprep.com/developer/docs/#Economic-Indicator. Note that adpEmployentChange is no longer an available datapoint. 

You can try this though: 


```
fmpc_get_url('economic?name=GDP&from=2019-10-10&to=2021-11-10&',api_version='4')

fmpc_get_url('economic?name=totalNonfarmPayroll&from=2019-10-10&to=2021-11-10&',api_version='4')

```

I am going to resolve this since it's not a bug with the code but related to FMP. In the next package update, I will add the economic end point.
